#!/usr/bin/env bash
# This script displays the content of the file /etc/passwd
IFS=:
while read -r line
do
	set $line
	echo "The user $1 is part of the $4 gang, lives in $6 and rides $7. $3's place is protected by the passcode $2, more info about the user here: $5"
done < /etc/passwd
